export const CREATE_TODO = "CREATE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const FETCH_TODOS = "FETCH_TODOS";
export const CREATE_CHILD_TODO = "CREATE_CHILD_TODO";
export const REMOVE_CHILD_TODO = "REMOVE_CHILD_TODO";
export const UPDATE_CHILD_TODO = "UPDATE_CHILD_TODO";
